import java.util.regex.Matcher
import java.util.regex.Pattern

def build_versions = [:]
build_versions.version_code = 56
build_versions.version_name = "4.1.0"
build_versions.min_sdk = 33
build_versions.target_sdk = 34
build_versions.build_tools = "34.0.0"
ext.build_versions = build_versions

ext.deps = [:]
def versions = [:]
versions.android_gradle_plugin = '7.4.2'
versions.android_maven_gradle_plugin = "2.1"
versions.booster = "3.1.0"
versions.booster_all = "1.1.1"
versions.annotation = "1.9.1"
versions.androidx_appcompat = "1.6.1"
versions.recyclerview = "1.4.0"
versions.material = "1.12.0"
versions.junit = "4.13.2"
versions.espresso = '3.6.1'
versions.constraint_layout = "2.2.0"
versions.glide = "4.16.0"
versions.rxjava2 = "2.2.21"
versions.rxandroid = "2.1.1"
versions.runner = "1.6.2"
versions.gson = "2.11.0"
versions.okhttp3 = "3.12.13"
versions.leakcanary = "2.14"
versions.lifecycle = "2.8.7"
versions.kotlin = '1.8.10'

//========xlibrary start========//
versions.xui = "dev~1.2.2-SNAPSHOT"
versions.xupdate = "2.1.5"
versions.xaop = "1.1.0"
versions.xutil = "2.0.0"
versions.xhttp2 = "2.0.10"
versions.xpage = "3.3.0"
versions.xrouter = "1.1.0"
//========xlibrary end========//

ext.versions = versions

def deps = [:]

def androidx = [:]
androidx.annotations = "androidx.annotation:annotation:$versions.annotation"
androidx.appcompat = "androidx.appcompat:appcompat:$versions.androidx_appcompat"
androidx.recyclerview = "androidx.recyclerview:recyclerview:$versions.recyclerview"
androidx.design = "com.google.android.material:material:$versions.material"
androidx.multidex = 'androidx.multidex:multidex:2.0.1'
deps.androidx = androidx

def xlibrary = [:]
xlibrary.xui = "com.github.pppscn:XUI:$versions.xui"
xlibrary.xupdate = "com.github.pppscn:XUpdate:$versions.xupdate"
xlibrary.xaop_runtime = "com.github.pppscn.XAOP:xaop-runtime:$versions.xaop"
xlibrary.xaop_plugin = "com.github.pppscn.XAOP:xaop-plugin:$versions.xaop"
xlibrary.xutil_core = "com.github.pppscn.XUtil:xutil-core:$versions.xutil"
xlibrary.xutil_sub = "com.github.pppscn.XUtil:xutil-sub:$versions.xutil"
xlibrary.xhttp2 = "com.github.pppscn:XHttp2:$versions.xhttp2"
xlibrary.xpage_lib = "com.github.pppscn.XPage:xpage-lib:$versions.xpage"
xlibrary.xpage_compiler = "com.github.pppscn.XPage:xpage-compiler:$versions.xpage"
xlibrary.xrouter_runtime = "com.github.pppscn.XRouter:xrouter-runtime:$versions.xrouter"
xlibrary.xrouter_compiler = "com.github.pppscn.XRouter:xrouter-compiler:$versions.xrouter"
xlibrary.xrouter_plugin = "com.github.pppscn.XRouter:xrouter-plugin:$versions.xrouter"
deps.xlibrary = xlibrary

def lifecycle = [:]
lifecycle.runtime = "androidx.lifecycle:lifecycle-runtime:$versions.lifecycle"
lifecycle.java8 = "androidx.lifecycle:lifecycle-common-java8:$versions.lifecycle"
lifecycle.compiler = "androidx.lifecycle:lifecycle-compiler:$versions.lifecycle"
lifecycle.viewmodel_ktx = "androidx.lifecycle:lifecycle-viewmodel-ktx:$versions.lifecycle"
lifecycle.livedata_ktx = "androidx.lifecycle:lifecycle-livedata-ktx:$versions.lifecycle"
deps.lifecycle = lifecycle

deps.android_gradle_plugin = "com.android.tools.build:gradle:$versions.android_gradle_plugin"
deps.android_maven_gradle_plugin = "com.github.dcendents:android-maven-gradle-plugin:$versions.android_maven_gradle_plugin"
deps.glide = "com.github.bumptech.glide:glide:$versions.glide"
deps.constraint_layout = "androidx.constraint:constraint-layout:$versions.constraint_layout"
deps.junit = "junit:junit:$versions.junit"
deps.runner = "androidx.test:runner:$versions.runner"
deps.rxjava2 = "io.reactivex.rxjava2:rxjava:$versions.rxjava2"
deps.rxandroid = "io.reactivex.rxjava2:rxandroid:$versions.rxandroid"
deps.gson = "com.google.code.gson:gson:$versions.gson"
deps.okhttp3 = "com.squareup.okhttp3:okhttp:$versions.okhttp3"
deps.leakcanary = "com.squareup.leakcanary:leakcanary-android:$versions.leakcanary"
deps.espresso = [:]
deps.espresso.core = "androidx.test.espresso:espresso-core:$versions.espresso"
deps.espresso.contrib = "androidx.test.espresso:espresso-contrib:$versions.espresso"
deps.espresso.intents = "androidx.test.espresso:espresso-intents:$versions.espresso"

ext.deps = deps

def isRelease() {
    Gradle gradle = getGradle()
    String tskReqStr = gradle.getStartParameter().getTaskRequests().toString()
    Pattern pattern
    if (tskReqStr.contains("assemble")) {
        println tskReqStr
        pattern = Pattern.compile("assemble(\\w*)(Release|Debug)")
    } else {
        pattern = Pattern.compile("generate(\\w*)(Release|Debug)")
    }
    Matcher matcher = pattern.matcher(tskReqStr)
    if (matcher.find()) {
        String task = matcher.group(0).toLowerCase()
        println("[BuildType] Current task: " + task)
        return task.contains("release")
    } else {
        println "[BuildType] NO MATCH FOUND"
        return true
    }
}
ext.isRelease = this.&isRelease

static def addRepos(RepositoryHandler handler) {
    handler.mavenLocal()
    handler.google()
    handler.mavenCentral()
    if (System.getenv('GITHUB_ACTIONS') == null) {
        handler.maven { url 'https://maven.aliyun.com/repository/google' }
        handler.maven { url 'https://maven.aliyun.com/repository/central' }
        handler.maven { url 'https://maven.aliyun.com/repository/public' }
    }
    handler.maven { url "https://repo1.maven.org/maven2/" }
    handler.maven { url 'https://oss.sonatype.org/content/repositories/public' }
    handler.maven { url "https://jitpack.io" }
}
ext.addRepos = this.&addRepos

project.buildscript.configurations.configureEach { configuration ->
    def dependencies = getProject().dependencies
    if (configuration.name.equals("classpath")) {
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xaop_plugin))
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xrouter_plugin))
        configuration.dependencies.add(dependencies.create("org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin"))
    }
}
